#pragma once

//Sample Scene
#define WINDOWSIZE 600.0f;


//HealthBar
#define MAXHEALTH 50;

//Lighting
#define NUMBEROFLIGHTS 4;

//Particles
#define PARTICLELIFETIME 0.5f;
#define PARTICLESPEED 1.0f;
#define PARTICLESPAWNDELAY 0.2f;

//PlayerObject
#define TELEPORTTIMER 1.0f;
#define FIRERATE 0.5f;
#define PLAYERSPEED 8.0f;
#define  PLAYERINVINCIBILITY 0.5f;

//Projectile
#define PROJECTILELIFETIME 3.0f;
#define PROJECTILETIMER 0.3f;
#define PROJECTILESPEED 6.0f;
#define HOMINGPROJECTILESPEED 3.0f;

//Magic Circle
#define MAGICCIRCLELIFETIME 550.0f;
#define MAGICCIRCLESPEED 200.0f;
#define MAGICCIRCLETIMER 7.0f;
#define MAGICCIRCLEATTACKTIMER 2.5f;
#define MAGICCIRCLESPAWNTIMER 1.0f;

//Lazer
#define LAZERLIFETIME 0.5f;
#define LAZERATTACKTIMER 0.8f;

//RedBoss
#define NUMBEROFPROJECTILES 50;
#define NUMBEROFMAGICCIRLES 3;
#define NORMALATTACKTIMER 3.0f;
#define EASYATTACKTIMER 10.0f;
#define BOSSTELEPORTTIMER 2.0f;


//Difficulty